- hosts: localhost
  gather_facts: false
  vars_files:
    - "vars/{{ecosystem}}.yml"
  vars:
    prepared_vpc_zones: "{{ build_vpc_zones_result['results'][0] }}"
    vpc_subnet: "{{ prepared_vpc_zones.vpc_subnet }}"
    vpc_zones: "{{ prepared_vpc_zones.vpc_zones }}"
    ami: "{{ ami_lookup_result['results'][0] }}"
    cfn_template_bucket: "{{ environments[region].cfn_template_bucket }}"
  roles:
    - role: build-vpc-zones
      vpc_environments:
        - "{{environments[region][environ] }}"
    - role: ami-lookup
      ami:
        - region: "{{region}}"
          ami_name: "intuitivetech-vpc-nat"
    - role: vpc
      vpc_parameters:
        Ecosystem: "{{vpc_ecosystem}}"
        Environment: "{{environ}}"
        NatKeyName: "{{environ}}-{{vpc_ecosystem}}-nat"
        NatImageId: "{{ ami.Image }}"
        VPCSubnet: "{{ vpc_subnet }}"
