- src: git+ssh://git@github.com/intuitivetechnologygroup/ansible-role-module-credstash.git
  name: credstash
  version: 1.0.0
- src: git+ssh://git@github.com/intuitivetechnologygroup/ansible-role-module-ami-lookup.git
  name: ami-lookup
  version: 1.0.0
- src: git+ssh://git@github.com/intuitivetechnologygroup/ansible-role-module-build-vpc-zones.git
  name: build-vpc-zones
  version: 1.0.0
- src: git+ssh://git@github.com/intuitivetechnologygroup/ansible-role-vpc.git
  name: vpc
  version: 1.0.0
